### ISSUE TITLE
some LR pairs were not present

### ISSUE THREAD

**Issue by Smilenone** [saezlab/liana#100]
I noticed that some LR pairs were not present for some celltype-pairs, i.e. for CD4T-B, I found NECTIN2-TIGIT LR pairs were not present in the result. Does this pairs were removed for thier low expression frequency in the corresponding celltypes?

And what if I want to save these LR pairs for ploting?

**Comment by dbdimitrov** [comment]
Hi @Smilenone,

Indeed liana will filter interactions with expr_prop lower than 0.1 by default. If you want to keep it check the `keep_all` parameter :)

Hope this helps.

**Comment by Smilenone** [comment]
Hi,


Thanks for your response, is the&nbsp;keep_all&nbsp;parameter&nbsp; in&nbsp;liana_wrap() function? Where can I find detalied description of this parameter?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saezlab/liana"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月6日(星期四) 晚上8:27
***@***.***&gt;;
抄送:&nbsp;"Qunlun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [saezlab/liana] some LR pairs were not present (Issue #100)





 
Hi @Smilenone,
 
Indeed liana will filter interactions with expr_prop lower than 0.1 by default. If you want to keep it check the keep_all parameter :)
 
Hope this helps.

**Comment by dbdimitrov** [comment]
?liana_wrap would do it :)
