### ISSUE TITLE
Error while installing liana

### ISSUE THREAD

**Issue by sidrahmaryam-cyber** [saezlab/liana#102]
Hello,
I am trying to install liana using 
remotes::install_github('saezlab/liana')

However I face this issue:
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

Can you please let me know the possible reason or solution. 
Thank you so much in advance.

**Comment by dbdimitrov** [comment]
Hi @sidrahmaryam-cyber,

I assume that it's an issue with a confilict in testthat versions


A solution is to install liana with a fresh R version (e.g. conda environment)

See these issues:
https://github.com/saezlab/liana/issues/73
https://github.com/nhanhocu/metamicrobiomeR/issues/4

Hope this helps.
Daniel

**Comment by sidrahmaryam-cyber** [comment]
Thank you so much for the response. However, I am still not able to install it. I tried various ways.
I created conda environment, tried installing, and getting same error. Without the conda, I tried installing in head R, same issue. 
I followed the steps in the link, still same problem. :( 

Regards,
Sidrah

**Comment by dbdimitrov** [comment]
Hi @sidrahmaryam-cyber,

In a replicated issue the author said that this worked for them by installing via source - e.g. glone and install locally. Hope this helps.

**Comment by EricDeveaud** [comment]
as usual R error message may be confusing.

PB is a combination of using UTF8 char in DESCRIPTION and locale environment//support 

just use plain ascii in DESCRIPTION file and installation goes smooth.

see:

```
> remotes::install_github("saezlab/liana")                                                                                                                                                                                                                                
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!
  ```
  
  versus 
  
  ```
> remotes::install_github("EricDeveaud/liana")
```

**Comment by dbdimitrov** [comment]
I have addressed this in the update that I will push today.
