### ISSUE TITLE
Error with liana_bysample

### ISSUE THREAD

**Issue by YYYYYWWWYYYYYY** [saezlab/liana#103]
Hello,
I was running liana_bysample and the problem happened :
Error: cannot allocate vector of size 8.4 Mb

I gsub the task with vf=30g,h_vmem=50g. 
I also run liana_wrap with the same data by sample, and the task was succeed.
Could you please tell me how to avoid the error when I use liana_bysample?

Thank you !

**Comment by dbdimitrov** [comment]
Hi @YYYYYWWWYYYYYY,

I'm not sure if I can help much without a reproducible example.
Happy to explore it further if I can reproduce your error.

Daniel
