### ISSUE TITLE
Downloading Liana in R 

### ISSUE THREAD

**Issue by sakinaamin** [saezlab/liana#109]
remotes::install_github('saezlab/liana')
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

I am unable to download the package in R due to the above error, could you please suggest how to troubleshoot?

**Comment by chkohler** [comment]
Problem confirmed on a fresh R 4.3.0 installation running Debian Buster:

> library(remotes)
remotes::install_github('saezlab/liana', upgrade="never", ref="master")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

>remotes::install_github('saezlab/liana')
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

---

`
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 10 (buster)

>Matrix products: default
BLAS/LAPACK: /linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so;  LAPACK version 3.8.0

>locale:
[1] C

>time zone: Europe/Berlin
tzcode source: system (glibc)

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] remotes_2.4.2

>loaded via a namespace (and not attached):
[1] compiler_4.3.0 tools_4.3.0    curl_5.0.0    
> 
`
