### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by supermegamio** [saezlab/liana#11]
Hello!

I just read the preprint and perform some preliminary cell-cell communication analysis with my data. I was wondering if exist any package or wrapper functions to perform a visualisation of the results. Or what do you actually use to plotting and integrate results?  

Thank you in advance

**Comment by dbdimitrov** [comment]
Hi supermegamio,

At its current state, liana does not provide any visualization options.

Yet , we are planning to bridge liana with [CrossTalkeR](https://github.com/CostaLab/CrossTalkeR) and possibly extend a bit the visualization options when working with a single condition.

I hope that helps.

**Comment by supermegamio** [comment]
Hi!

Thank you for you quick response :)

I will explore the possibilities with CrossTalkeR

**Comment by ccruizm** [comment]
Hello!

I would like to know if you have any suggestions on how to format the data and input it in CrossTalkeR. For instance, if I use `liana_wrap`, the tutorial mentions that aggregate_rank can be used as P value. Should I use this value for visualization purposes? Do you have any preliminary code that one could share to use the output from liana and generate the plots using CrossTalkeR, please? 

Thanks in advance!

**Comment by dbdimitrov** [comment]
Hi @ccruizm,

Yes, I am also planning to use the p-value for visualizations. However, this will likely come at a later stage.

@jsnagai is the person who could help with CrossTalkeR the most and I believe there is some preliminary code to integrate the two tools :)

**Comment by ccruizm** [comment]
Thanks for your reply! @jsnagai do you have any preliminary code to visualize the results from `liana_wrap` that you could share, please?

Many thanks!

**Comment by dbdimitrov** [comment]
Hey,

Took while for me to get to this but LIANA now provides a flexible dotplot function.
Feel free to open an issue if any other specific type of plot would be useful.
