### ISSUE TITLE
Error in liana_tensor_c2c

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [saezlab/liana#110]
Hi ! I got : 

Error in system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE, :
error in running command

Setting up Conda Environment with Basilisk
Error in system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE,  : 
  error in running command

5 | system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE, stderr = FALSE)
4 | installConda()
3 | obtainEnvironmentPath(env)
2 | basilisk::basiliskStart(liana_env, testload = "scipy.optimize")
1 | liana_tensor_c2c(sce = Bladder_data_sce, score_col = "LRscore", how = "outer", conda_env = NULL)

How can I resolve this @dbdimitrov ?

**Comment by dbdimitrov** [comment]
Hi, 

it seems that you're likely using an outdated version of basilisk.
See related issue: https://github.com/LTLA/basilisk/issues/24

Hope this helps.

**Comment by BenjaminDEMAILLE** [comment]
I'm on Mac M1

**Comment by BenjaminDEMAILLE** [comment]
this one provoc the bug : 

> basilisk.utils::installConda()
Error in system2(python.cmd, c("-E", "-c", shQuote("print(1)")), stdout = TRUE,  : 
  error in running command

same directly in console 

I have : v1.11.2 of basilisk.utils
