### ISSUE TITLE
MEBOCOST DB Integration

### ISSUE THREAD

**Issue by relgamal** [saezlab/liana#114]
Hello,

Thank you for putting together a useful package with great Tensor-cell2cell integration. It appears that previous iterations of cell2cell have integrated the MEBOCOST database including metabolite-sensor pairs. Is it possible to include this database as part of LIANA?

Thank you,

Ruth

**Comment by dbdimitrov** [comment]
Hi @relgamal,

Thanks for using liana. Its a bit more complicated than just including the database, as mebocost additoonally estimates metabolite abundances. With this in mind, we hope to have an alternative database and method for metabolite-mediated communication in liana soon

**Comment by relgamal** [comment]
Hi @dbdimitrov,

Thank you for your response, I look forward to testing out that update once available!

Ruth
