### ISSUE TITLE
LIANA for bulk RNA seq with separated cell samples

### ISSUE THREAD

**Issue by ngutrinh** [saezlab/liana#115]
Can I apply LIANA bulk RNA seq with separated cell samples?

**Comment by dbdimitrov** [comment]
Hi,

Do you mean sorted cells according to cell types then sequenced together?

If so, liana would not be directly applicable, however there is an example of using the liana database for bulk here:
https://decoupler-py.readthedocs.io/en/latest/notebooks/bulk.html

Hope this helps.

**Comment by ngutrinh** [comment]
Yes, I have sorted cells according to cell types
The link is great. Thank you so much!

**Comment by dbdimitrov** [comment]
👌
