### ISSUE TITLE
can Liana works with Seurat V5 assay?

### ISSUE THREAD

**Issue by jessicaliu70** [saezlab/liana#119]
can Liana works with Seurat V5 assay?

**Comment by dbdimitrov** [comment]
Hi @jessicaliu70,

I haven't tried it, but I had a quick look at the Seuratv5 tutorials and it seems like the preserve the standard assay structure, i.e. data and counts are still there; and in reality this is what liana will extract from a Seurat object. 

If you try it and experience any issues, I'm happy to update it to work with Seurat.
