### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by rstorch01** [saezlab/liana#120]
I am trying to install liana in R/4.0.2 using remotes::install_github("saezlab/liana")

The installation fails with:  Error: object ‘homologene_download’ is not exported by 'namespace:OmnipathR'
Execution halted

I had previous installed OmnipathR using Biocmanager::install("OmnipathR").  Please let me know how I can resolve this issue.

**Comment by dbdimitrov** [comment]
Hi,

Please install OmnipathR via github. This should solve the issue!

**Comment by dbdimitrov** [comment]
Hi @rstorch01,

Can you try installing OmnipathR also from Github? This should resolve it. Let me know if it doesn't. 

Daniel

**Comment by rstorch01** [comment]
The install did not work:
* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘join_by’ is not exported by 'namespace:dplyr'
Execution halted
ERROR: lazy loading failed for package ‘OmnipathR’
* removing ‘/usr/local/R/4.0.2/lib64/R/library/OmnipathR’
* restoring previous ‘/usr/local/R/4.0.2/lib64/R/library/OmnipathR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmpcg2EQa/file618330fc912b/OmnipathR_3.9.6.tar.gz’ had non-zero exit status

**Comment by dbdimitrov** [comment]
@rstorch01 can you please try installing OmniPath via Github using `remotes::install_github("saezlab/OmnipathR")`?

**Comment by dbdimitrov** [comment]
Hmm, this seems like an OmniPathR issue @deeenes
