### ISSUE TITLE
handling gene symbol

### ISSUE THREAD

**Issue by Erfan1369** [saezlab/liana#123]
Dear LIANA Developers,

I would like to express my gratitude for creating such a powerful tool. I have a question that may seem quite basic but is essential for my analysis.

I am working with single-cell RNA-seq data from mice and I'm interested in exploring the various methods and resources offered by LIANA. However, I'm uncertain about how to handle the gene symbols. Specifically, do I need to convert all the gene symbols in my seurat object to their human orthologues ? I am also wondering if there is an option to consider the reverse, i.e., analyzing the data in its native organism without conversion.

Could you kindly advise me on whether it's possible to select the organism type during the analysis within LIANA? 
Thank you
Erfan

**Comment by dbdimitrov** [comment]
Hi @Erfan1369,

Many thanks for using liana.

Have you seen this tutorial: https://saezlab.github.io/liana/articles/liana_ortho.html

Let me know if this is what you're looking for.

Daniel

**Comment by Erfan1369** [comment]
Hi Daniel,

I appreciate your help and quick response,

yes the tutorial is what I was looking for,

I will comeback to you if there was a major problem!

Regrads

**Comment by dbdimitrov** [comment]
@Erfan1369 happy to hear that. Feel free to open more issues if anything else comes up :)
