### ISSUE TITLE
Issue in installation

### ISSUE THREAD

**Issue by youngorchuang** [saezlab/liana#124]
When I run the following codes:
library(devtools)
install_github('saezlab/liana')

It shows:
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

How can I fix this issue?

**Comment by dbdimitrov** [comment]
Hey,

There was a related issue recently:
https://github.com/saezlab/liana/issues/102

Unfortunately, I haven't been able to reproduce the error, so I cannot debug it. Let me know if e.g. installing via source works.
