### ISSUE TITLE
Can Liana work on csv files 

### ISSUE THREAD

**Issue by Samir1703** [saezlab/liana#125]
Hey, I'm very new (literally started yesterday) to all this and I have almost no idea what I'm doing. I want to run ligand receptor analysis on a single cell dataset I have. I basically only have a csv file containing the genes and their relative expression per cluster. Can I run a Liana analysis on that csv or does it need to be a seurat object ?

**Comment by dbdimitrov** [comment]
Hi @Samir1703,

LIANA would indeed require a Seurat or SingleCellExperiment object as input. So, you might need to convert the csv to those.

**Comment by Samir1703** [comment]
Hello @dbdimitrov ! Thank you for your reply :) 
As I said I'm very new to all this. Would creating a seurat object out of a csv file containing gene expression per cluster work ?
Something that goes like that 
Gene, Cluster 1, Cluster 2, Cluster 3
GeneA, ValueA1, Value A2 ...etc
 
Basically I annotated my single cell using cloupe and extracted the raw data for my manual annotation but in that I lose the data for individual cells and only have cluster gene expression

Any insight would help

Thanks

**Comment by dbdimitrov** [comment]
Hi @Samir1703,

Liana requires the information about individual cells to work, specifically it requires a count table with normalised counts and a corresponding cluster label for each cell.

Hope this helps.
