### ISSUE TITLE
Any domcuments for CCC method developers? 

### ISSUE THREAD

**Issue by shenscore** [saezlab/liana#129]
In other word, is there anyway to **benchmark a new CCC method** by using LIANA?

**Comment by dbdimitrov** [comment]
Hi @shenscore,

Likely the easiest way would be via the OpenProblems repo, where we reproduced and extended the benchmark described in the liana manuscript:
https://github.com/openproblems-bio/openproblems/tree/main/openproblems/tasks/_cell_cell_communication

Hope this helps :)
