### ISSUE TITLE
Liana R vs Liana py versions

### ISSUE THREAD

**Issue by KyriakisDimitrios** [saezlab/liana#134]
Hello, 
Thank you very much for this amazing tool.
I would like to know if the recent 
Liana_R version 0.1.11 means Liana_py v 0.1.11 or 
Liana_R v0.1.11 == Liana_py v1.0.3
Thanks

**Comment by dbdimitrov** [comment]
Hi Dimitrios,

There is no connection of the versions between python and R. Though, the single-cell component of Liana-py is of course highly consistent with the latest version in R. 

Eventually, our idea is to transition the backend of the R package to the more efficient (and now more comprehensive) python package. Essentially, to call liana-py via liana-R :)

Hope this helps.

Daniel

**Comment by KyriakisDimitrios** [comment]
Thanks! 
 One more question about the R version. The rank_aggregate does not have the arguments like the python version has. 
 Is it running with the default hyperparams of python ? 
 e.g
 expr_prop=0.1, 
 min_cells=5,
 n_perms=1000,
 
 I tried to find the parameters in the github but I did not manage
 
 Thanks again

**Comment by dbdimitrov** [comment]
In R, these parameters are passed to `liana_wrap` and rank_aggregate only aggregates the results from different methods. In Python rank aggregate does both.
