### ISSUE TITLE
CCC between condition

### ISSUE THREAD

**Issue by apal6** [saezlab/liana#138]
Hi,

Thank you for the package. I have three conditions and in each condition i have three samples. I want to look at communication between three major clusters. I followed the tutorial on https://saezlab.github.io/liana/articles/liana_tutorial.html and was able to get through the analysis but now I want to split it between my conditions to look at major signaling happening before and after treatment. I wonder if it's possible? Thank you!

**Comment by dbdimitrov** [comment]
Hi @apal6,

We recently made extensive protocols that would fit your complex design: 
https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_R/QuickStart_pbmc.html

Hope this helps.

**Comment by apal6** [comment]
@dbdimitrov thank you. I wonder if it would also support two conditions only? I have pre and post paired samples and another condition which is post only samples. 

Would you recommend subsetting the pre and post and running the liana pipeline on this first and then on post only sample?

**Comment by dbdimitrov** [comment]
Hi @apal6,

The analysis above would support two conditions only, alternatively you could try this one (essentially doing differential contrast between post vs pre), though it's available currently only in Python:
https://liana-py.readthedocs.io/en/latest/notebooks/targeted.html
