### ISSUE TITLE
liana_tensor_c2c batch effects

### ISSUE THREAD

**Issue by daymecita** [saezlab/liana#139]
I just recently tested tensor-cell2cell with LIANA following the R tutorial from here: https://saezlab.github.io/liana/articles/liana_cc2tensor.html. 
I have 10 samples, 7 disease and 3 healthy. I had integrated all of them using Seurat and next annotated the cell types.  
I first ran liana_bysample using the sca method. Then I ran liana_tensor_c2c. My sce (converted from Seurat) object doesn't have corrected counts. I did log normalized the counts, though. The issue is that I am getting only one signicant factor **(factor 2)** that seems to be capturing batch effects, since the samples PsA6 and 7 were processed along with the HD 1,2, and 3 and they cluster together according to the loadings (see image below). Do we need to use corrected counts in tensor-c2c? How does it account for batch effects? 

![Contexts_heatmap_tensor](https://github.com/saezlab/liana/assets/100194518/24d4d7eb-b244-45ca-a622-62dc60d21621)

This is my code: 

`sce <- liana_bysample(sce = sce,
                      sample_col = "context",
                      idents_col = "CellID_l1",
                      method = "sca", # we use SingleCellSignalR's score alone
                      expr_prop = 0, # expression proportion threshold
                      inplace=TRUE, # saves inplace to sce
                      return_all = FALSE # whether to return non-expressed interactions 
)`
`sce <- liana_tensor_c2c(sce = sce,
                        score_col = 'LRscore',
                        rank = 7,  # set to None to estimate for you data!
                        how='outer',  #  defines how the tensor is built
                        conda_env = NULL, # used to pass an existing conda env with cell2cell
                        use_available = FALSE # detect & load cell2cell if available
)`

**Comment by dbdimitrov** [comment]
Hi @daymecita,

You could perform batch correction with e.g. scVI or COMBAT prior to running LIANA+ on the normalised counts. Though, it is also possible that these approaches might also remove some of the biological signal. 

We (@hmbaghdassarian) showcase scVI in this supplementary note: https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_R/S1_Batch_Correction.html; along with a series of detailed workflows detailing LIANA and Tensor-cell2cell.

**Comment by rbutleriii** [comment]
Hey @dbdimitrov and @hmbaghdassarian, thanks so much for putting this together. Currently running through this and I have thoroughly confused myself thinking `liana_by_sample` runs on (batch.corrected) counts. But then in S1_Batch_Correction I see the `log1p` call, so it must be on logcounts, yes? `liana_wrap` specifies NULL by default 

In any case, in case it is helpful, here is how I approached multiple batch effects:
```r
suppressPackageStartupMessages({
  library(data.table)
  library(Seurat)
  library(patchwork)
  library(tidyverse)
  library(SingleCellExperiment)
  library(reticulate)
  library(magrittr)
  library(liana)
  library(Cairo)
  library(decoupleR)
  library(ggplotify)
  # library(sva)
  library(zellkonverter)
  library(optparse)
})

...

# define the liana environment
c2c <- import("cell2cell")
# adding scvi support
scvi <- import("scvi", convert = FALSE)
scipy <- import("scipy.sparse")

# gpu copnfiguration
if (gpu){
    device <- 'cuda:0'
    tensorly <- reticulate::import('tensorly')
    tensorly$set_backend('pytorch')
    scvi$settings$dl_pin_memory_gpu_training <- TRUE
}else{
    device <- NULL
}

...

# basic feature filtering
sce <- sce[rowSums(counts(sce) >= 1) >= 5, ]

# scVI batch correction
if (batch) {
  # prep for scVI
  scvi$settings$seed = as.integer(888)
  colnames(colData(sce)) <- gsub("\\.", "_", colnames(colData(sce)))

  # setup
  print("Converting SCE to AnnData...")
  adata <- SCE2AnnData(sce, X_name = "counts")
  adata$X <- scipy$csr_matrix(adata$X)
  
  print("Setting up scVI with separate batch keys...")
  scvi$model$SCVI$setup_anndata(
    adata,
    batch_key = "soup",  # Primary batch effect (0 or 1)
    categorical_covariate_keys = c("batch", "orig_ident")  # Additional batches
  )

  adata
  
  # build a model and train for batch correction
  print("Creating scVI model...")
  model <- scvi$model$SCVI(
    adata,
    n_latent = 30L,           # latent dimensions
    n_layers = 2L,            # neural network depth
    gene_likelihood = "nb",   # negative binomial
    dropout_rate = 0.1
  )
  
  # Rule of thumb for A100 40GB:
  # - Small dataset (<50K cells): batch_size = 1024-2048
  # - Medium dataset (50K-200K cells): batch_size = 512-1024  
  # - Large dataset (>200K cells): batch_size = 256-512
  # - Very large (>500K cells): batch_size = 128-256
  print("Training model on GPU (this may take several minutes)...")
  model$train(
    max_epochs = 400L,
    early_stopping = TRUE,
    plan_kwargs = list(lr = 0.001),
    batch_size = 512L,        # increase for GPU (default is 128)
    accelerator = "gpu",      # PyTorch Lightning accelerator
    devices = 1L,             # number of GPUs to use
    datasplitter_kwargs = list(
      pin_memory = TRUE,   # Pin memory for faster GPU transfer
      num_workers = 4L     # Number of CPU workers for data loading
    )
  )
  
  print(model$history)

  # Store corrected counts back
  print("Saving batch adjusted counts...")
  adjusted_counts <- t(
    model$get_normalized_expression(
      library_size = 1e4,
      return_numpy = TRUE,
      batch_size = 512L  # use same batch size for inference
    )
  )
  dimnames(adjusted_counts) <- dimnames(sce)  # Restore names
  print(adjusted_counts[1:10, 1:10])
  counts(sce) <- adjusted_counts

  # Clear GPU memory
  torch$cuda$empty_cache()
  torch$cuda$synchronize()
  rm(adjusted_counts, model, adata)
  gc()
}
```
So I think then I just need that to be `logcounts(sce) <- log1p(adjusted_counts)` to put it in the right slot, and specify `assay = logcounts` for `liana_by_sample`.

**Comment by dbdimitrov** [comment]
Hi @rbutleriii, 

Seems right - scvi is lib-normalizing, so with the log1p you should be good. I'd still check the count / cell distributions, but this makes sense 👍

**Comment by liezeltamon** [comment]
Hi @dbdimitrov and @hmbaghdassarian,

Following up on this, is it also valid to apply `scanpy.pp.combat()` on the log-normalised values from the scanpy workflow and feed that to `li.mt.rank_aggregate.by_sample()`?

```
    li.mt.rank_aggregate.by_sample(
        adata,
        sample_key=sample_key,
        groupby=label_key,
        resource_name="consensus",
        layer="log1pcp10k-batch_corrected",
        use_raw=False, # Run on log- and library-normalized counts
        n_perms=10000,
        verbose=True,
        inplace=True,
        expr_prop=liana_expr_prop,
        n_jobs=n_cores#,
        # Defaults to note
        #expr_prop=0.1, # Must be expressed in expr_prop fraction of cells
        #min_cells=5,
        #seed=1337
    )
```

**Comment by hmbaghdassarian** [comment]
Hi @liezeltamon:

Combat introduces negative counts values, which is problematic both for CCC inference and downstream non-negative tensor decomposition.

If you use it, you'll have to replace the negative values in your counts matrix with 0 prior to running the pipeline (or with a very small value if you still want those interactions to exist). This may not have a substantial impact on the final tensor decomposition output if you are running the entire pipeline, as the negative counts represent lower expression values anyways and we've found tensor decomposition to be pretty robust to missing values and zero-ing out negative counts. But it does certainly skew your batch-corrected counts distribution. 

This issue is discussed in the README [here](https://github.com/hmbaghdassarian/tc2c_benchmark/tree/main/notebooks/batch_correction) and the analyses surrounding "Question 4A" [here](https://github.com/hmbaghdassarian/tc2c_benchmark/blob/main/notebooks/batch_correction/02_analyses.ipynb), alongside the discussion of Fig. S5f in the [paper](https://doi.org/10.1016/j.crmeth.2024.100758).
