### ISSUE TITLE
Are frequency heatmaps comparable between conditions

### ISSUE THREAD

**Issue by Carolina-Toste** [saezlab/liana#143]
Hi, thank you so much for such a great package.

I've been trying to use liana to compare cell-cell communication within my dataset of three conditions. And I was wondering how are the frequency of interactions calculated?

If I subset my Seurat into the different conditions and run the liana pipeline for each would the frequency heatmaps be comparable between conditions (even if for example I have a different number of cells in one condition)?

Thank you!

**Comment by dbdimitrov** [comment]
Hi @Carolina-Toste, apologies for the delayed response. I only noticed the issue now.

The frequency is quite simpe, it just counts the number of ~significant interactions. For comparisons between conditions I would recommend trying out one protocol with Tensor-cell2cell: https://github.com/saezlab/ccc_protocols

https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(24)00089-4

**Comment by mainharryHR** [comment]
I have the same difficulties. I am exploring the strategies too. Please let me know if know how to do 3 or 4 conditions. 

Thanks
