### ISSUE TITLE
Omnipath extension

### ISSUE THREAD

**Issue by lindsdudley** [saezlab/liana#147]
Hi liana group,

Thank you so much creating this amazing resource. I am trying to extend this to using omnipath to look at specific pathways. I am able to get the omnipath data but I am a little confused about the liana inputs it requires.testdata <-
    [readRDS](https://rdrr.io/r/base/readRDS.html)([file.path](https://rdrr.io/r/base/file.path.html)(liana_path , "testdata", "input", "testdata.rds"))

I have an RDS from saving the end of my liana resources but I am confused what the "test_data" and "input" are supposed to be.

Could you please advise?

**Comment by dbdimitrov** [comment]
Hi @lindsdudley,

Can you please share which tutorial is this from? Input data is usually a SingleCellExperiment or Seurat object. Does this help?
