### ISSUE TITLE
Filter OmnipathDB for ligand/receptors

### ISSUE THREAD

**Issue by ccruizm** [saezlab/liana#15]
Good day!

I would like to filter ligands and receptors that are only present in the surface/cell membrane and not take into account soluble factors, among others.

Is there a way to filter those when using the OmnipathDB? 

Thanks for your help!

**Comment by deeenes** [comment]
Hi Cristian,

You can do something like this:

```{r}
library(liana)
library(OmnipathR)
library(dplyr)
library(purrr)

ligands <-
    OmnipathR::import_omnipath_intercell(
        parent = c('ligand', 'cell_surface_ligand'),
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30,
        entity_types = 'protein'
    ) %>%
    pull(genesymbol) %>%
    unique

receptors <-
    OmnipathR::import_omnipath_intercell(
        parent = 'receptor',
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30,
        entity_types = 'protein'
    ) %>%
    pull(genesymbol) %>%
    unique

ligand_receptor <-
    liana::compile_ligrec() %>%
    map(
        function(lr){
            lr$transmitters %<>% filter(genesymbol %in% ligands)
            lr$receivers %<>% filter(genesymbol %in% receptors)
            lr$interactions %<>% filter(
                source_genesymbol %in% ligands &
                target_genesymbol %in% receptors
            )
            return(lr)
        }
    )
```

See details here: https://saezlab.github.io/OmnipathR/reference/import_omnipath_intercell.html, https://saezlab.github.io/OmnipathR/reference/intercell_consensus_filter.html. And also: https://saezlab.github.io/OmnipathR/reference/import_intercell_network.html, https://saezlab.github.io/OmnipathR/reference/filter_intercell_network.html, although `liana` doesn't use the latter two but only for the OmniPath combined database, not for individual resources.

It's good to double check all the parameters above: do you want only proteins classified as ligands, or any potential transmitter which is membrane bound? Are the consensus filters too strict? Do you want only proteins, or also protein complexes?

Best,

Denes

**Comment by ccruizm** [comment]
Thank you very much for the quick reply! I plan to use spatial transcriptomics to confirm potential interactions assessed by the in silico inferred interactions on the single-cell transcriptomics data. For that reason, I would like to use only proteins on the cell surface and can be linked to direct cell-cell communication (before jumping into paracrine/autocrine interactions).

What would you recommend I should include in that case?  I think that I should also include any potential transmitter that is membrane-bound. The list of options from `get_intercell_categories()` is quite extensive. Do you have any suggestions of key categories that should be included? I assume it is also good to include protein complexes. 

About the consensus cutoffs, I think the ones you suggested are good! I would like to include potential interactions that have higher confidence based on supporting literature. 

I plan to use the filtered ligands/receptors with `liana_wrap` running two or three methods. In that case, should I reformat the resource differently? or the one you shared would suffice?

Thanks again!

**Comment by deeenes** [comment]
In this case, just a few modifications:

```
ligands <-
    OmnipathR::import_omnipath_intercell(
        causality = 'trans',
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30
    ) %>%
    pull(genesymbol) %>%
    unique

receptors <-
    OmnipathR::import_omnipath_intercell(
        causality = 'rec',
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30
    ) %>%
    pull(genesymbol) %>%
    unique
```

In the `transmitter` and `receiver` categories we already collected those subcategories which have the potential to deliver signal from or to the cell. Maybe for the receivers you can use only the transmembrane ones ("pmtm") as peripheral proteins might deliver a signal only indirectly. About the consensus thresholds, I think you will see, if the results contain many obviously wrong interactions, you can try again with stricter thresholds.

How to pass this to `liana_wrap`, I think @dbdimitrov can tell us.

**Comment by dbdimitrov** [comment]
Hi Denes,

Perhaps, what would be easiest is to give me a day or two to implement the required function in `liana`.  Having a customizable OmniPath resource is something I plan to do anyway. :)

Also, just wanted to note something regarding the complexes. It is important to keep in mind that only some of the methods implemented in liana (namely Squidpy and CellChat) would make use of those. The rest will simply not match any interactions containing complexes. I am working on re-implementing the methods for exactly this limitation.

I will come this ASAP.

Best,
Daniel

**Comment by ccruizm** [comment]
Great! thank you very much @deeenes  and @dbdimitrov for the useful tips and help. I will wait for the new function to give it a try.

**Comment by dbdimitrov** [comment]
Hi @ccruizm,


```
library(liana)
library(OmnipathR)
library(dplyr)
library(magrittr)
library(purrr)

liana_path <- system.file(package = "liana")
seurat_object <-
    readRDS(file.path(liana_path , "testdata", "input", "testdata.rds"))

# filter only PM ligs and regs
ligands <-
    OmnipathR::import_omnipath_intercell(
        causality = 'trans',
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30
    ) %>%
    pull(genesymbol) %>%
    unique

receptors <-
    OmnipathR::import_omnipath_intercell(
        causality = 'rec',
        topology = c('pmtm', 'pmp'),
        consensus_percentile = 50,
        loc_consensus_percentile = 30
    ) %>%
    pull(genesymbol) %>%
    unique

# get omni and filter
pm_omni <-  select_resource("OmniPath")[[1]] %>%
    filter(source_genesymbol %in% ligands &
               target_genesymbol %in% receptors)

# Run with tools
squidpy_results <- call_squidpy(seurat_object,
                                op_resource = pm_omni)

connectome_results <- call_connectome(seurat_object = seurat_object,
                                      op_resource = pm_omni)
```

It might take me a bit more time to change the general structure of liana and write a vignette.

In the meantime, I propose using the slightly modified code from above.

**Comment by ccruizm** [comment]
Hello @dbdimitrov,

I have tried the run the modified code you kindly shared but I am having troubles either using the `liana_wrap` function or each individual tool (this case `call_squidpy`) but got the next errors:

With `liana_wrap`
```
Error in if (nc != ncol(y)) {: argument is of length zero
Traceback:

1. liana_wrap(reference, method = c("connectome", "cellchat"), resource = pm_omni, 
 .     squidpy.params = list(cluster_key = "celltype_squidpy", threshold = 0.25, 
 .         .seed = 1004), connectome.params = list(p.values = TRUE), 
 .     cellchat.params = list(nboot = 10, exclude_anns = NULL, assay = "RNA", 
 .         .seed = 1004, .normalize = FALSE, .do_parallel = FALSE, 
 .         .raw_use = TRUE))
2. setdiff(resource, c(get_resources(), "all"))
3. setdiff.data.frame(resource, c(get_resources(), "all"))
4. check_compatible(x, y)
5. is_compatible_data_frame(x, y, ignore_col_order = ignore_col_order, 
 .     convert = convert)
```

and running `call_squidpy`

```
Error in UseMethod("select"): no applicable method for 'select' applied to an object of class "character"
Traceback:

1. call_squidpy(reference, cluster_key = "celltype_squidpy", threshold = 0.25, 
 .     .seed = 1004, op_resource = pm_omni)
2. map(op_resource, function(x) x %>% select(uniprot_source = source, 
 .     unprot_target = target, source = source_genesymbol, target = target_genesymbol, 
 .     category_intercell_source, category_intercell_target)) %>% 
 .     unname()
3. unname(.)
4. map(op_resource, function(x) x %>% select(uniprot_source = source, 
 .     unprot_target = target, source = source_genesymbol, target = target_genesymbol, 
 .     category_intercell_source, category_intercell_target))
5. .f(.x[[i]], ...)
6. x %>% select(uniprot_source = source, unprot_target = target, 
 .     source = source_genesymbol, target = target_genesymbol, category_intercell_source, 
 .     category_intercell_target)
7. select(., uniprot_source = source, unprot_target = target, source = source_genesymbol, 
 .     target = target_genesymbol, category_intercell_source, category_intercell_target)
```

This issue seems associated when using the wrap or squidpy (it ran with `call_connectome` and `call_cellchat`). Is there something else I should consider to run this part properly? 

Thanks!

**Comment by dbdimitrov** [comment]
Hi @ccruizm,

Regarding `liana_wrap`, I need to make some changes to the function itself to work, as it currently requires character class as input for the resources (e.g. "OmniPath").

On the other hand, you can pass a list directly to `call_squidpy`. Also, if you update liana to its latest version, it should also work with a tibble - I have recently changed the way that `call_squidpy` works to amend for this inconsistency and issue that you're observing.

Best,
Daniel

**Comment by ccruizm** [comment]
Hello! I had installed the last liana version. I re-installed it (well, forced the installation since my version hadn't changed since the last update) and still get the same error when using `call_squidpy`. `pm_omni` is indeed a tibble. When you mentioned that I could pass a list, I am not sure what you meant by that (something like `omni_list <- list(pm_omni)`?). Sorry if this is a trivial question. 

Thanks!

**Comment by dbdimitrov** [comment]
Hi Christian,

My bad! I did not realize that I have made the change only to my development branch. I have now appropriately made the change to the main branch also.

Alternatively, as you suggest you can pass it the following way:

omni_list <- list("placeholder" = pm_omni)

Regards,
Daniel

**Comment by dbdimitrov** [comment]
Hi @ccruizm,

Please find the customizable OmniPath vignette /w LIANA here:
https://saezlab.github.io/liana/articles/liana_custom_op.html

I did this along with the re-implementation of some of the methods + enabling them to take complexes into account (see more info on the updated readme :)).

I hope you find this helpful!

**Comment by ccruizm** [comment]
Thank you very much @dbdimitrov! Great implementation. It will definitely be of huge help! 

I will test it soon!
