### ISSUE TITLE
Database form clarification

### ISSUE THREAD

**Issue by Tianyi409** [saezlab/liana#153]
Hi Daniel,

Thank you for your package, it is very helpful for studying intercellular communication.
I tried to add my dataset to liana for analysis before but failed many times. Luckily, I finally found out why. Because my data comes from mice, and the databases you analyze are all human databases. IN THIS CASE, the case letters for the same gene are distinguished from the mouse gene "Gata3" and the human gene "GATA3". Therefore, I recommend that you clarify this fact in the tutorial. Also, could you please update the mouse database?

PS, I prefer Death Knight to Paladin

**Comment by Tianyi409** [comment]
My mistake, I have seen your mouse consensus in Resource, which I dont use before. Maybe you can mention it in tutorial, Cuz in the tutorial Consensus is only the Human database

Additionally, can I ask you some meaning of the colname which the LIANA give to me? The "aggregate rank", "Mean Rank" and "LRscore"?

For the Horde!

**Comment by dbdimitrov** [comment]
aggregate_rank would be a probability distribution calculated with the RobustRankAggregate method of the ranks across different ligand-receptor methods. Mean rank is just the mean rank across different ligand-receptor methods, while LRscore is an expression magnitude score as calculated by SingleCellSignalR :)
