### ISSUE TITLE
liana_tensor_c2c Errors 

### ISSUE THREAD

**Issue by mainharryHR** [saezlab/liana#157]
Dear everyone,

Thanks for great package. 
I am following the tutorial https://saezlab.github.io/liana/articles/liana_cc2tensor.html,
But I encountered errors. My gut feeling is that this error might be related to the names between arguments. After rename, there is another errors: 

_Building the tensor using LRs...
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Columns must be same length as key_

Please help to figure out. Thank you all:)

`sce <- liana_tensor_c2c(sce = Sce,
                        score_col = 'LRscore',
                        rank = NULL, 
                        how='outer',  
                        conda_env = NULL,
                        use_available = FALSE 
                        )`

_Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: Expected a 1D array, got an array with shape (0, 5)_

`reticulate::py_last_error()`
_KeyError: '**LRs'**_

**Comment by dbdimitrov** [comment]
Perhaps, it's best if you follow the notebook I referred you to in the other issue. It seems here that there might be some issue with the liana results stored in the sce object.

Let me know if following the other notebook fixes the issue.

Best wishes,
Daniel
