### ISSUE TITLE
Multiple comparison, such as 3 or 4 conditions 

### ISSUE THREAD

**Issue by mainharryHR** [saezlab/liana#158]
Dear everyone,

I have 3 comparisons in my dataset. It seems the Liana 0.1.12 only support 2 comparisons for now. Should I subset the 2 conditions each time from Seurat or singleCellExperiment object? which might affect the statistical test. But I believe it has minor effects of statistics after subsetting. 

It seems people has already discussed this issue before, but the strategies are still not very clear to me. :)

Any comments are welcome.

Thank you all.

Best,

**Comment by dbdimitrov** [comment]
Hi @mainharryHR,

LIANA when combined with Tensor-cell2cell supports any number of comparisons. I would refer you to this tutorial: https://ccc-protocols.readthedocs.io/en/latest/notebooks/ccc_R/QuickStart.html, along with the detailed vignettes that go over the same process but more in depth.

Essentially, the way this analysis works is that it's agnostic of any condition as it is unsupervised. So, technically you are assuming that if your conditions are indeed primary drivers of changes in CCC, then you should capture those in an unbiased (unsupervised) manner.

Hope this helps :)

Daniel

**Comment by mainharryHR** [comment]
Thank you for the suggestions.
I tried pipeline based on the tutorial, It seems the multiple comparison only apply to one plot `pwc <- pwc %>% add_xy_position(x = "condition") ggboxplot,` **but not for other plots**, such as `heatmap`, `c2c$plotting$ccc_networks_plot`, `gsea.dotplot`, 

After `ggboxplot`, should I subset samples again in order to do other plot?

Many thanks

Best

**Comment by dbdimitrov** [comment]
Hi @mainharryHR,

See the factors and hence factor loadings that you get are summaries of the signal across all your samples. So, the plots do work across an indefinite number of conditions as long as you have some factor that captures differences according to your conditions :)

**Comment by mainharryHR** [comment]
Thank you for the information. How should plot the heatmap in for 3 different comparisons?
`liana::plot_lr_heatmap(sce = TcellsLiana,  n = 8)`, I can not find the arguments to tell the `conditions`

Best,

**Comment by dbdimitrov** [comment]
Hi @mainharryHR, 

So, I think the point is that this analysis doesn't necessarily do that as the tensor decomposition is an unsupervised process indepedent of the condition labels. 

You can think of this as being similar to PCA, except rather than having principle components, you have factors that are linear combinations of the patterns in your data.

If the sample/context loadings separate your conditions in a specific factor, then the loadings in the other dimensions of that factor are also associated to the condition.

I hope this helps a bit :)

**Comment by mainharryHR** [comment]
Thank you for the fast response and important information.

I guess if I really want to plot the heatmap or dot plot, I need to subset the 2 conditions from seurat object.

Have a nice day and thank you for the nice packages.
