### ISSUE TITLE
heat_freq question

### ISSUE THREAD

**Issue by vkartha** [saezlab/liana#161]
Hi there - I had a naive question related to the output shown in heat_freq. How do I interpret the sender and receiver cells having different definitions (i.e. barplot of cell counts not the same for a given cell type) here,  given that all Liana is using as input is a specification of the single grouping variable (e.g. celltype annotation / current Indent grouping var in seurat object). There is no actual specification of what the sender/receiver cells are for a given cell type, for this to be different in the output? (of course I do expect the heatmap to be assymetrical due to directionality of sender-receivers). I assumed it is performing all by all categories (when not specified in wrapper function), but I wasn't expecting it to further separate out  / infer sender and receiver cells within a given cell type on it's own. How does it do the latter internally?

Sample plot from tutorial where barplot frequencies on rows/columns not the same for single cell type
![image](https://github.com/saezlab/liana/assets/9615730/c6b859cd-daa3-419f-8bd7-3625c736b58c)

**Comment by dbdimitrov** [comment]
Hi @vkartha,

The heatmap quite literally counts interactions by cell type as sender and receiver. I included it because of frequent requests. A cell type missing as source or receiver will not show up, hence they can be different.

**Comment by vkartha** [comment]
Ohh my bad, so those barplots are literally just row/column sums, and not cell counts or something orthogonal to the heatmap info. Thanks for the clarification

**Comment by dbdimitrov** [comment]
Hi @vkartha, yes, exactly :)
