### ISSUE TITLE
Different Interactions coming up when using Ramilowski2015 and Omnipath resources

### ISSUE THREAD

**Issue by paulyashna** [saezlab/liana#21]
Hi @deeenes  and @dbdimitrov,

I have a question about the database resources being used by Liana. I tried using 'Ramilowski2015' and 'Omnipath' in separate Liana runs but with the same input seurat object and and same methods (liana_aggregate).

In the output interactions with 'Omnipath' I miss some interactions that come up has top significant ones when using only 'Ramilowski2015'. I would have expected the same interactions to also be significant in the 'Omnipath' run; may be not at the top but at least be there in the list.  Is there some kind of prioritization within Omnipath for
 these resources that eliminates some interactions? I am not able to figure out the reason for this.

I would appreciate your input.

Thanks,
Yashna

**Comment by dbdimitrov** [comment]
Hi Yashna,

Indeed, OmniPath is a bit more than the union of all resources as we have filtered it according to localisation consensus and according to curation. If you wish to get a bit more details on the way that we filtered or to create a more promiscuous OmniPath version I suggest having a look at this tutorial:
https://saezlab.github.io/liana/articles/liana_custom_op.html

Best,
Daniel

**Comment by paulyashna** [comment]
Hi Daniel,

So just to be clear when I select the resource 'Omnipath' during a LIANA run, it is actually 'Omnipath: as used in the Liana manuscript'; and NOT the unfiltered and original 'Omnipath' resource. Is that correct?

Best Regards,
Yashna

**Comment by paulyashna** [comment]
Hi Daniel,

So just to be clear when I select the resource 'Omnipath' during a LIANA run, it is actually 'Omnipath: as used in the Liana manuscript'; and NOT the unfiltered and original 'Omnipath' resource. Is that correct?

Best Regards,
Yashna

**Comment by dbdimitrov** [comment]
hi @paulyashna,

1. Correct.
2. At this stage OmniPathR does not provide a function to do that, but it is something that is planned to be implemented. However, technically it shouldn't be much different than the conversion of genes in any other set. 

I hope this helps.

Best wishes,
Daniel

**Comment by dbdimitrov** [comment]
@paulyashna, FYI we had a discussion on this issue and its something that we will aim to implement in the near future :)

I will keep you posted.

**Comment by paulyashna** [comment]
hi @dbdimitrov ,

Thanks for letting me know. It will be great to be able to compare mouse and human interactions. Until now I just convert mouse Ids to human gene names in the Seurat count matrix.

On another note, on using 'generate_omni' , I have been getting:

Error: 'filter_intercell_network' is not an exported object from 'namespace:OmnipathR'

Do you have an idea what may be causing this?

Thanks for your time.
Best Regards,
Yashna

**Comment by dbdimitrov** [comment]
Hi Yashna,

I believe it's the Omnipath version that you're using. I suggest updating it to the latest one on github.

Best wishes, 
Daniel

**Comment by paulyashna** [comment]
Thanks a lot I updated both OmnipathR and Liana, and generate_omni works smoothly.

**Comment by dbdimitrov** [comment]
Hi @paulyashna,

Just wanted to let you know that I have written a temporary solution for conversion of OmniPath interactions to mouse symbols. It is not ideal, but it might be worth a shot in the meantime.

You can find it here:
https://github.com/saezlab/liana/issues/22#issuecomment-928067888

Best wishes,
Daniel

**Comment by paulyashna** [comment]
Thanks for this update @dbdimitrov. I will try this out in the coming days and mention if I have a feedback.
