### ISSUE TITLE
New 'cytotalk' implementation error

### ISSUE THREAD

**Issue by Projectnix** [saezlab/liana#24]
Hi @dbdimitrov,

I've attempted the new 'cytotalk' implementation on my Seurat object via the wrapper, and it seems to error out with the following message:

```Centering and scaling data matrix
  |=============================================================================================================| 100%
Inf introduced into PEM score, is the data log1p tranformed?
LIANA: LR summary stats calculated!
Now Running: Cytotalk
Centering and scaling data matrix
  |=============================================================================================================| 100%
Error: Problem with `mutate()` column `receptor.pem.min`.
i `receptor.pem.min = exec(complex_policy, (.data[["receptor.pem"]]))`.
i `receptor.pem.min` must be size 1, not 0.
i The error occurred in group 1: source = "B", target = "B", ligand.complex = "ADAM10", receptor.complex = "CADM1".
```

For the record, my default assay is the 'RNA' slot and I lack any kind of transformation in that slot as I use 'SCTransform' to do my normalization/scaling, which makes its own separate slot. I'm not sure if the error is because of that, however.

Any ideas?

This is my code currently:

```library(Seurat)
library(liana)
ola <- readRDS("ola_combined.RDS")
DefaultAssay(ola) <- "RNA"
liana_test <- liana_wrap(ola,
                         method = c("cytotalk"),
                         resource = c('OmniPath'),
                         # CellChat requires normalized data
                         cellchat.params = list(.normalize=TRUE))
saveRDS(liana_test, "LianaOla.RDS")
```

**Comment by dbdimitrov** [comment]
Hi @Projectnix,

Indeed. It seems likely that error occurs, as liana by default uses the RNA assay with the normalised data slot.
I would suggest changing the assay to "SCT", by passing assay ="SCT" to the `liana_wrap` call.

Also, there is no need to pass normalize=TRUE to the cellchat parameters, if you have already normalised your data. 

It's important to note that the cytotalk implementation includes the CytoTalk Crosstalk score, but not the downstream network analysis.

Let me know how it goes :)

**Comment by Projectnix** [comment]
That seems to have worked!

Do you foresee any issues with running LIANA on the "RNA" slot for all the other implementations/algorithms, and running it on the "SCT" slot for the 'cytotalk' implementation before combining the two and feeding it into liana_aggregate?
 
I believe the authors of Seurat recommend performing most downstream analysis on the raw, non-scaled data in the $RNA@data slot rather than the transformed SCT slot, which is why I've been pointing liana_wrap at the 'RNA' slot thus far.

**Comment by dbdimitrov** [comment]
Hi @Projectnix,

`liana_aggregate` is used to combine the results from different methods.

I believe that it largely depends on what downstream analysis you would like to perform. In the case of LIANA, I'd suggest using the log-transformed counts (i.e. those that are typically stored in `RNA@data` (which in your case were not present since you apply SCT). `SCT`-transformation is an alternative to log-transforming your counts and hence LIANA should also be applicable with it. 
However, little is known how different normalization approaches would affect the different scores - this is perhaps a miny project on its own :)

I hope this helps.

**Comment by dbdimitrov** [comment]
@Projectnix Also, I have now appropriately changed the name to Crosstalk scores, as in reality we do not support the whole cytotalk tool :)
