### ISSUE TITLE
Mouse data?

### ISSUE THREAD

**Issue by the6science** [saezlab/liana#27]
Hi there! Liana seems great and I have no problem running it on human data. However, using the default parameters, every mouse dataset I have tried comes up with receptors or ligands that are just F3, F7 or F10. Do I need to specify species somewhere in the code?

**Comment by dbdimitrov** [comment]
Hi,

Yes, by default LIANA uses human symbols, so you would need to convert them to murine.

I describe and provide a code snippet how to do so here:

https://github.com/saezlab/liana/issues/22#issuecomment-928067888

I hope this helps!
