### ISSUE TITLE
interfacing with seurat

### ISSUE THREAD

**Issue by wfma** [saezlab/liana#3]
Hello! I just saw your preprint on this and was very excited to try. Can you shed some light on whether we can run this pipeline within R/Rstudio on our seurat objs? We currently have a few datasets that would benefit from comparing several tools, but we are unsure how to interface it through the command line terminal.

Thanks,
Wei

**Comment by dbdimitrov** [comment]
Hi,

Thanks a lot for the interest.

You should be able to run the methods via R/Rstudio, given you have enough RAM. All of the methods, except NATMI, work with sparse matrices and I was able to run them with ~20,000 cell Seurat objects on my local PC with 16GB RAM.

I think for now it would be best if you follow [this example](https://github.com/saezlab/ligrec_decoupler/blob/master/analysis_scripts/cbmc_analyse/cbmc_run.R). Also, from the landing page/readme, you will see how to install all of the dependencies (R package for the R-based methods and an .yml file for the Python-based Squidpy/NATMI).

I plan to provide a wrapper function to run multiple methods as well as well to containerize the framework in the future.

Best wishes,

Daniel

**Comment by wfma** [comment]
Dear Daniel,

Thank you for the reply! Sounds great. I will try this example. Yes unfortunately my python skill needs some catching up to do. I look forward to the wrapper functions, I think it will be a really strong point to add to your paper!

Wei
----------------------------------------------------
Wei Feng Ma
University of Virginia
School of Medicine
Medical Scientist Training Program
Miller Lab, G2
C: (207)-329-8393

**Comment by dbdimitrov** [comment]
Hi Wei,

As discussed previously, I have implemented a wrapper function for the package (liana) and have also provided a short [tutorial](https://saezlab.github.io/liana/articles/liana_tutorial.html).

I've made quite a few changes to the stability of the package, made the installation more straightforward, and you can also obtain a rank consensus from the different methods. You can also directly interface a processed Seurat object with LIANA :).

This is still very much work in progress, but I hope it helps!

Any feedback is more than welcome!

Best wishes,
Daniel
PhD Candidate/Student
Saezlab
Heidelberg University

**Comment by wfma** [comment]
this is really amazing! I cant wait to try this! I will close this request now and follow up once I try it :)
