### ISSUE TITLE
how can liana be applied to mouse dataset?

### ISSUE THREAD

**Issue by Wulin-Tan** [saezlab/liana#30]
Hi, Liana is perfect for investigating the CCC. but how can it be applied to mouse dataset?
Thanks a lot.

**Comment by dbdimitrov** [comment]
Hi @Wulin-Tan,

Thanks. I recently wrote this tutorial on conversion to murine orthologs:
https://saezlab.github.io/liana/articles/liana_ortho.html

I hope this helps.

Best,
Daniel

**Comment by dbdimitrov** [comment]
Note that a human-murine dictionary is also implemented in LIANA.

**Comment by Wulin-Tan** [comment]
Hi, @dbdimitrov 
I just saw that tutorial, it is wonderful! 
thank you very much.

**Comment by trudy89** [comment]
@dbdimitrov  I tried https://saezlab.github.io/liana/articles/liana_ortho.html 
it doesn't work, a lot of errors.
could you successfully run following code?
op_resource <- select_resource("Consensus")[[1]]
ortholog_resource <- generate_homologs(op_resource = op_resource,
                                       target_organism = 10090) # mouse

**Comment by jreimertz** [comment]
@trudy89 I was able to get this to work by installing from this PR https://github.com/saezlab/liana/pull/174

```
remotes::install_github('saezlab/liana#174')
```

As mentioned in this issue #170
