### ISSUE TITLE
Vizualization options 

### ISSUE THREAD

**Issue by Fransis11** [saezlab/liana#34]
Hello, 

Thanks for making this useful tool! 

I'm not an expert but I am trying to explore Liana in order to prove that my results are not resource-specific. I was wondering, are there visualization options other than the dotplots? 

Thank you! 

Best regards, 

Francesca

**Comment by dbdimitrov** [comment]
Hi @Fransis11,

Thanks for opening an issue and for the kind comment.

Indeed, currently liana provides only a basic dotplot.
I do plan to extend visualization options as this is one of the most requested features, so I'm open to suggestions.

Daniel

**Comment by Fransis11** [comment]
Hi @dbdimitrov, 

Thanks for the quick and nice answer. I can suggest something like circle plot or heatmaps (like in cellchat) or similar. Also, is there a way to know with which cell types a specific cell type mainly interacts?

Thanks a lot!

Francesca

**Comment by dbdimitrov** [comment]
Hi @Fransis11,

I have now included a frequency heatmap to the tutorial, inspired by CellChat and CellPhoneDB.
I also suggest caution when interpreting such a heatmap :).

I will continue adding more visualizations to LIANA, but these will be part of it's long-term developments.

Daniel

**Comment by Fransis11** [comment]
Hi @dbdimitrov ,

Thanks a lot for your useful and quick implementation, good luck for the future developments! 

Francesca
