### ISSUE TITLE
call_cellchat trouble with liana_aggregate?

### ISSUE THREAD

**Issue by austinv11** [saezlab/liana#36]
Hello, I am using liana 1.1 and I am using a custom resource with a few methods in LIANA, including call_cellchat. However, it seems that the output of call_cellchat does not match what is expected in liana_aggregate as it is missing the ligand.complex and receptor.complex columns that are present in other outputs. Image of the outputs below:

![image](https://user-images.githubusercontent.com/6373756/166732263-00962ee6-b19a-4624-a452-67a0d5b71397.png)

**Comment by dbdimitrov** [comment]
Hi @austinv11,

I just pushed a hotfix to address the issue.

**Comment by austinv11** [comment]
Just reinstalled, seems to work now. Thank you for the prompt fix!
