### ISSUE TITLE
Issue with scconnect

### ISSUE THREAD

**Issue by austinv11** [saezlab/liana#38]
Hello, when I try to use the Scconnect, I get the following error from liana:

`Error: trying to get slot "columns" from an object of a basic class ("NULL") with no slots`

Is there anything I need to do to prevent this from happening?

**Comment by dbdimitrov** [comment]
Hi @austinv11,

I implemented scconnect when testing methods in liana, but decided against including it.
So, scconnect won't run as only it's scoring function is implemented, but it is not meant to be part of the methods in liana.

You can see the available ones via `show_methods()`.

I will remove the redundant code to avoid any confusion in liana's next update.

Thanks,
Daniel

**Comment by austinv11** [comment]
Ah, I understand. Thanks for the information.
