### ISSUE TITLE
Docker version of liana

### ISSUE THREAD

**Issue by bitcometz** [saezlab/liana#41]
Hello，

Could you provide  a version of liana?
I found it very good software, but it is difficult to install.

Best

**Comment by dbdimitrov** [comment]
Thanks @bitcometz,

Do you refer to LIANA's R package, or the development version (https://saezlab.github.io/liana/articles/liana_devel.html)?

**Comment by bitcometz** [comment]
Thanks ！！！
It is a great software ！！！

**Comment by dbdimitrov** [comment]
Hey @bitcometz,

LIANA is now available at dockerhub, along other lab toos, under tanevski/saezverse (https://hub.docker.com/u/tanevski).

Hope that helps!

Daniel

**Comment by bitcometz** [comment]
Great ！！！
