### ISSUE TITLE
Interpretation of Odds Ratio

### ISSUE THREAD

**Issue by ebasto** [saezlab/liana#45]
High, I have a question about the interpretation of Odds Ratio, not exactly code but maybe this is a good place to ask. The LIANA publication says

"Notably, a high agreement with cytokine activities was observed for CellChat and CellPhoneDB in the HER2 + dataset, when considering all of their predictions subsequent to false-positive filtering (vertical line in Fig. 6A), highlighting the value of the false-positive control steps of these methods."

In the image below the HER2+ dataset is the yellow one.

<img width="301" alt="Screen Shot 2022-07-11 at 3 45 19 pm" src="https://user-images.githubusercontent.com/12102945/178214151-99697f76-ee91-4216-b401-9f30d499ad97.png">

The yellow lines for CellChat and CellPhoneDB start with a very low odds ratio, which gradually increases as the range of ranked interactions is increased (side note here: I'm confused about whether the range is 1:100, 100:200, etc. or 1:100, 1:200, etc.). 

So my main question is, I thought that high agreement would look the opposite. i.e. in high agreement the top interactions (where 1 is the highest) display a high Odds ratio, gradually decreasing as you increase the range. Would greatly appreciate it if you could clarify this for me!

Thanks, 
Edgar

**Comment by dbdimitrov** [comment]
Hi @ebasto,

I believe my idea here is that when you consider all interactions after filtering (vertical lines), both methods perform better than random.

I calculate odds rations as 1:100, 1:250, 1:1000 - idea being that the lower they go the signal usually disappears (as seen for the other methods). CellChat and CellPhoneDB are exceptions in the sense that neither method's "mean" score is intended to be ranked, while the remainder of the methods are. That is why I highlight the fact that when you filter to their thresholds they perform better than random (yellow and purple lines).

In general, I really tried to highlight that these results simply highlight that the methods would generally capture signal, but the benchmarks and the signal have their own limitations, so I would not over-interpret the results.

Hope this helps!

Daniel
