### ISSUE TITLE
Specificity and magnitude columns across methods.

### ISSUE THREAD

**Issue by enblacar** [saezlab/liana#47]
Hi Liana developers,

First of all, thanks for providing such an amazing package! The fact that one can run different Ligand-Receptor on the go and retrieve everything nicely packed in a long-format tibble is priceless!

I would like to make use of the package for custom visualization purposes, and I am wondering which columns from the different experiments are the ones that point to the specificity (size of the dots, how statistically significant the interaction is) and the magnitude (color of the dots, how strong the interaction is).  After going through the outputs, this is what I could gather:

```
 # Each method have a different column name.
  specificity <- list("cellphonedb" = "pvalue",
                      "natmi" = "edge_specificity",
                      "logfc" = "none",
                      "sca" = "global_mean",
                      "connectome" = "none",
                      "aggregated" = "aggregate_rank")
  
  magnitude <- list("cellphonedb" = "lr.mean",
                    "natmi" = "prod_weight",
                    "logfc" = "logfc_comb",
                    "sca" = "LRscore",
                    "connectome" = "weight_sc",
                    "aggregated" = "mean_rank")
```

Where "none" means that I could not find a suitable column for it and "aggregated" means from the output of `liana::liana_aggregate()`. Could I get some feedback whether these are the right columns and what to include (if any) in the missing ones?

Also, I noticed that the output  of `liana::liana_aggregate()` removes the ligand and receptor columns and maintains the ligand.complex and receptor.complex ones. Is this intentional and, if one wants to generalize plot generation from liana's output, would it be more appropriate to use the complex columns even for single-method experiments?

Many thanks in advance for the feedback!

**Comment by dbdimitrov** [comment]
Hi Enrique,

The package looks very cool. Overall, if I could suggest anything would be to maybe just stick to the `liana_aggregate` output. Really then the user can pick how to best approach the results. 1) You can filter by CellPhoneDB p-value or the aggregate_rank probabilities, 2) Rank interactions by magnitude /w NATMI's edge weights, 3) Use LRscores for magnitude as they are easy to intepret and comparable across datasets.

By p-values, I meant the DE p-values for the ligand and receptors separately, otherwise for the interaction it would need to be the CellPhoneDB p-value. :)

**Comment by enblacar** [comment]
Hi Daniel,

Thanks for the feedback!  I will work on it based on your suggestions.

Best,
Enrique

**Comment by dbdimitrov** [comment]
Hey @enblacar,

Check out the `rank_method` function :)

**Comment by enblacar** [comment]
Hi @dbdimitrov 

Thanks a lot for implementing the function! 

In my use case, I ended up expecting a consensus liana object from the user, and then analyzed the data as you suggested in the comments above. `rank_mehtod` looks really cool! For what I have seen, it generates a ranking based on "specificity" or "magnitude" for the desired individual methods. That will definitely help with the processing of the results for plotting.

From my point of view and without truly knowing how hard would it be to implement, I could envision some additions to this function:
- First, whenever possible, interactions could be also ranked by a combination of specificity-magnitude or magnitude-specificity. This is, for example in cellphoneDB, specificity-magnitude will order first by p-value and then by lr.mean. And the opposite would be true for magnitude-specificity. 

- Second. Would it be possible to get a similar approach for a multi-method liana result object? This is, aggregating the results into a single matrix and then ordering them based on the approach you suggested above.

- Finally. I could also see helpful, provided that this is a helper function that does not necessarily need to be run, that there could be a parameter that can be toggled on that would rename (or duplicate, showing the user which were the actual columns meant to be used), based on the method, the relevant columns as "magnitude" and "specificity". In the case of cellphonedb, those would be, again, lr.mean and p-value. I think this would be truly helpful for the final plotting, provided that the user wants to use this data for any other visualization purposes outside the ones already implemented on liana. 

Thanks again for your quick feedback and enhancements on this great package!

Enrique

**Comment by dbdimitrov** [comment]
Hi @enblacar,

These are all points that I've also thought in the past. I see nothing stopping anyone doing the 1st point, but I'd prefer to keep them separate in LIANA (I think it's already a bit confusing /w all the methods).

Your second point makes a lot of sense - my only cocern is the same as /w the point above. I will indeed try to implement `liana_aggregate` to do specificity or magnitude in an easier way in the following updates, so I could also just include a "both" option that returns the aggregate of either :)

Your third point makes a lot of sense, I should make a function that at least prints them out in a clear manner :)

Best,

Danie
