### ISSUE TITLE
liana_dotplot magnitude and specificity argument syntax

### ISSUE THREAD

**Issue by mschmidt22** [saezlab/liana#49]
I am attempting to set my own scaling values for the liana_dotplot. Thus, I am entering the values I want into the magnitude and specificity arguments

liana_adult_signaling %>%
  liana_dotplot(source_groups = c('Fibroblast'),
                target_groups = c('Beta'),
                ntop = 10, magnitude  = 1, specificity = 0.2)

However, I get the following error. Thus, can you please explain the proper syntax for the magnitude and specificity arguments?

Error in `as_indices_impl()`:
! Must rename columns with a valid subscript vector.
✖ Can't convert from <double> to <integer> due to loss of precision.
Run `rlang::last_error()` to see where the error occurred.

**Comment by mschmidt22** [comment]
I am now realizing that the magnitude and specificity arguments are supplying data for the graph and not scaling the legend. I imagine this is something I will have to do with ggplot

**Comment by dbdimitrov** [comment]
@mschubert indeed! If you wish to scale the dotsizes, you can pass a vector with those to `size_range`-  c(2, 10) by default.
