### ISSUE TITLE
Seurat version dependency for installation

### ISSUE THREAD

**Issue by ajwilk** [saezlab/liana#5]
Hi there, noticed that liana requires Seurat version <=3.2.3. Is there a way to remove this dependency (seems to be coming from liana, not one of the other CCC pipelines)? I have v4 installed and am guessing that others will run into this issue. Thanks much!!

```
> devtools::install_github('saezlab/liana')

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Seurat’ 4.0.2 is being loaded, but <= 3.2.3 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
```

**Comment by dbdimitrov** [comment]
Hi thanks for opening an issue.

I had set the Seurat version to 3.2.3 intentionally, as some of the packages were previously not updated to work with Seurat v4.

I have now appropriately bumped up the code and you should be able to run liana with the latest Seurat version as well as v3.2.3.

Best,
Daniel

**Comment by ajwilk** [comment]
Apologies I had missed your reply! Yes, all is working now for me thanks!
