### ISSUE TITLE
Filtering for secreted ligands

### ISSUE THREAD

**Issue by c-felton** [saezlab/liana#50]
Hi,

I was wondering if there was a way to break results down into secreted ligands, cell-cell interactions and ECM-cell interactions?

Many thanks,
Cath

**Comment by dbdimitrov** [comment]
Hi @c-felton,

There is yes, I touch on how one could create a resource /w only membrane-bound interactions here:
https://saezlab.github.io/liana/articles/liana_custom_op.html

So, with a few lines one could filter LIANA's results to only membrane-bound interactions.

Hope this helps! :)

**Comment by c-felton** [comment]
Thanks, this is really helpful. I can see how I could do this :)
