### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by mimisikai** [saezlab/liana#51]
This is what I got when installing:
> remotes::install_github('saezlab/liana')
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'liana' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 58/60
  Rate limit reset at: 2022-08-30 20:34:12 UTC

**Comment by dbdimitrov** [comment]
@mimisikai https://github.com/r-lib/devtools/issues/1566

**Comment by dbdimitrov** [comment]
@mimisikai did trying this resolve the issue?

**Comment by mimisikai** [comment]
> @mimisikai did trying this resolve the issue?

Yes. Thanks!
