### ISSUE TITLE
Can liana do the analysis for Spatial Transcriptomics data？

### ISSUE THREAD

**Issue by bitcometz** [saezlab/liana#53]
Hello，thanks for this great software.

Can I use liana to do the analysis for Spatial Transcriptomics data？

Could you give some suggestions ?

Thanks !!!

**Comment by dbdimitrov** [comment]
Hey @bitcometz, 

Yes, you could. Any type of transcriptomics data would work as long as it comes with annotated cells/spots.

However, if you wish to make full use of spatial information I would recommend checking out misty 😊 or perhaps Giotto's spatCellCellcom as a simpler option.

**Comment by bitcometz** [comment]
thanks ！！！
