### ISSUE TITLE
weird error 

### ISSUE THREAD

**Issue by rachel662** [saezlab/liana#55]
Hi there 
I am trying to run Liana and I get this error 

`Expression from the `originalexp` assay will be used
Running LIANA with `colLabels`/`Idents` as labels (matching column in metadata not found).`

would you be able to help with this at all? 
thanks 
Rachel

**Comment by dbdimitrov** [comment]
Hi @rachel662,

Is it an error or just a warning/message? :)

I print `labels (matching column in metadata not found)` when the Idents(seurat) are not found in any of the columns in the metadata.

**Comment by rachel662** [comment]
Hi there, 
I think in this case should i make a column in the metadata the Idents? Would that solve this warning error as currently it hasn't worked correctly

**Comment by rachel662** [comment]
thanks for your help on this also

**Comment by dbdimitrov** [comment]
So there might be something else that is causing an error

**Comment by rachel662** [comment]
Hi there, 
the idents currently aren't the cell type annotations which is why I think it hasn't worked properly? but if I make the column in the metadata that has the cell type in it the idents do you think it would solve the issue? (sorry I don't think i was clear in my last comment) 
cheers, 
Rachel

**Comment by dbdimitrov** [comment]
Hi @rachel662,

I believe so, yes. :)

You can either reset Idents, or alternatively pass the name of the idents column that you wish to use via the `idents_col` param.

Hope that helps.
Daniel

**Comment by rachel662** [comment]
Hi 
I have successfully made the Idents a column in my metadata but I still get this warning 
`Expression from the `originalexp` assay will be used
Running LIANA with `colLabels`/`Idents` as labels (matching column in metadata not found).`

Do you know why I get it? I have tried to make sure that the active.idents slot is copied from the metadata column with my cell type annotations? 

Cheers, 
Rachel

**Comment by rachel662** [comment]
For some more context in case that's helpful when I get the table at the end, I get these as ligand complexes and receptor complexes 
![image](https://user-images.githubusercontent.com/63318678/191574586-0bcab777-9735-4a46-8e84-812a49c079c3.png)


thanks so much for your help again, 
Rachel

**Comment by rachel662** [comment]
and when I run the dot plot command I get this error 
`liana_dotplot(source_groups = c("F"),target_groups = c("M"),ntop = 20)
Error in `combine_vars()`:`

Do you know why this might be happening? 

Cheers, 
Rachel

**Comment by dbdimitrov** [comment]
Hmmm,

Are you by any chance using non-human data?
If yes, there is a tutorial on how to convert liana's resource to other model organisms :)

Regarding the metadata column - maybe if you have it in your metadata it's better to just specify the name of the column.

Daniel

**Comment by rachel662** [comment]
Hi there, 
I successfully managed to run LIANA but it came up with this error? 
I was using mouse mgi gene names but converted to mouse hgnc 

`Error: cannot allocate vector of size 479 Kb`

would you be able to help me with this at all? 

thanks again, 
Rachel

**Comment by dbdimitrov** [comment]
Hi @rachel662,

Hmmm, now this is a weird error 🤣

If you send me a subset of your data, I can check on my pc.

Daniel.dimitrov@uni-heidelberg.de

Best wishes,

Daniel

**Comment by rachel662** [comment]
Hi Daniel, 
thanks, i can try to do that yes, from looking it up it seems like it's a memory error?
and I need to allocate more memory to my Rstudio? 

Cheers, 
Rachel

**Comment by dbdimitrov** [comment]
Hi @rachel662,

I find it unlikely that 400Kb would be an issue. 🤔

**Comment by rachel662** [comment]
Hi there 

I think it was a memory issue as I allocated loads of memory to R and left it running overnight and it seems to have successfully run 

however when plotting the graphs using the liana_dotplot function I get this error? 

Error in `combine_vars()`:
! Faceting variables must have at least one value
Run `rlang::last_error()` to see where the error occurred

do you know why this might be? 
thanks again for all your help with this 
Rachel

**Comment by dbdimitrov** [comment]
Hi @rachel662,

Maybe it would be easier if you can share the code and the output of liana :)
