### ISSUE TITLE
Something error when qsub tasks in linux

### ISSUE THREAD

**Issue by YYYYYWWWYYYYYY** [saezlab/liana#58]
Hi there
When I qsub R script  in linux, it always pointed out Error and could not allocate vector of size XXX Mb. 
However, It's ok when I run this script in jupyter.
How should I write liana script and qsub it in linix avoiding similar errors?
Thanks in advance!

**Comment by dbdimitrov** [comment]
Hi @YYYYYWWWYYYYYY,

If liana works on the same environment in Jupyer, I would say its likely that you need to request more ram on your cluster.

I previously have ran LIANA via qsub and on slurm.

**Comment by dbdimitrov** [comment]
A source of the issue might be incompatibilities of your BioC SingleCellExperiment-related packages, so I would recommend updating scater/scuttle and SCE to their latest possible update for your R version :)
