### ISSUE TITLE
How to do Differential CCC analysis?

### ISSUE THREAD

**Issue by fbnrst** [saezlab/liana#59]
I am wondering whether and how differential cell-cell communication (CCC) analysis could be performed with LIANA. I imagine the following situation. I have a single cell RNAseq dataset for two conditions (e.g. control and treatment) and the same cell types are present in both conditions. Cell type composition and transcriptomic state are slightly different for both conditions. For simplicity, let us say I am interested in the communication of two cell types A & B. I hypothesize that there are are differences in CCC between those cell types for conditions control and treatment. Now, I can run LIANA for both conditions. Would you have a suggestion for how to screen the results for meaningful differences in CCC?

**Comment by dbdimitrov** [comment]
Hi @fbnrst,

I have answered this in some detail here:
https://github.com/saezlab/liana/issues/32

In short, I am working on extending LIANA to a number of ways to do differential CCC.
However, it's also plausible to use LIANA at it's current state for DCCC.

For example, if you run liana per sample, you could then easily do differential CCC /w e.g. simple wilcoxon between conditions on LRscores (I have noted that this is very consistent /w e.g. dimensionality reduction techniques).
Alternatively, if you run LIANA by condition, you could also directly compare the ranks obtained for the same interaction in different conditions.

Hope this helps and I hope that I will be able to push my dev branch soon, as this is a commonly reoccurring question :)

**Comment by fbnrst** [comment]
Thanks a lot for the suggestions and for the link to #32, I really appreciate this.!
