### ISSUE TITLE
Running `liana::liana_aggregate()` on a multi-method output produces a byproduct `omnipath-log` folder in the current working environment.

### ISSUE THREAD

**Issue by enblacar** [saezlab/liana#61]
Hi @dbdimitrov,

I would like to point out a behaviour I have experienced with liana, that I was able to pinpoint the source recently.

Every time I run `liana::liana_aggregate()`, in my case in a multi-method output, this produces a folder called `omnipath-log` in my current working environment. Is this an intended behaviour? If so, is there a parameter that handles where this folder is created?  Or, on the opposite side, is there a parameter that prevents this folder from being created? Any of the two would be highly appreciated!

I am sorry, not being able to tell you exactly which line of code generates this, probably has to do with the `logger.R` function. 

Best,
Enrique

**Comment by deeenes** [comment]
To disable `OmnipathR` logging into a file just make sure the option `omnipath.logfile` is `"none"`. You can add the lines below to the file `./omnipathr.yml` or `~/.conf/OmnipathR/omnipathr.yml`:

```{yml}
default:
  omnipath.logfile = none
```

Or set the following shell variable:

```{bash}
export OMNIPATH_LOGFILE="none"
```

**Comment by dbdimitrov** [comment]
Hi @enblacar,

Thanks for pointing this out.

Indeed. At this stage, it's just a left-over from the benchmark. I will likely just remove the logger in the next update. 

Best wishes, 

Daniel

**Comment by enblacar** [comment]
Hi @deeenes, @dbdimitrov,

The options suggested worked great, thanks!

Best,
Enrique
