### ISSUE TITLE
Error in "auto_copy()" 

### ISSUE THREAD

**Issue by AltayYuzeir** [saezlab/liana#63]
Hello,
I have created a working LIANA pipeline, and now I try to run it using a new dataset.
I get an error in auto_copy() from liana_wrap(), see the image below. This seurat file was v2, so I ran UpdateSeuratObject function, if that is relevant.

![liana](https://user-images.githubusercontent.com/34285813/195031667-3bcd03ae-b194-4b78-8775-0409db7501dd.jpeg)

**Comment by dbdimitrov** [comment]
Hi @AltayYuzeir,

I have not encountered this error, and I don't explicitly call auto_copy() - it's internal meaning that likely a join is failing at some point.

I see that liana does not find any matching columns in the metadata to your `Idents()`, I would suggest to double check those.

**Comment by dbdimitrov** [comment]
If provided with a subset of your data, I could try to reproduce and resolve the error.

**Comment by AltayYuzeir** [comment]
Good morning,

Thank you for taking the time to sort this out! I really appreciate it. I set the Idents with the Idents() function and the "celltype" column in the meta data. Here is a donwsampled data. 
https://uni-bonn.sciebo.de/s/htrz2HJoafOClom

**Comment by dbdimitrov** [comment]
Hi @AltayYuzeir,

I was able to run your data with the following code:

```
sobj <- readRDS("~/Downloads/Seurat_downsample/seurat_downsample.rds")
res <- liana_wrap(sobj, idents_col = "celltype", permutation.params=list(nperms=100))
res <- res %>% liana_aggregate()
```

I would suggest updating liana to the latest version (0.1.7) and the giving a short the data when you pass the column explicitly via `idents_col`.

The error that you encounter comes from the dplyr package, so perhaps updating it also is a good idea.

**Comment by AltayYuzeir** [comment]
Thank you for looking into the matter! The code you have provided indeed runs. 
In my case, I use external resource of a mouse, using your Orthology Conversion tutorial.
In this case, I get the same error about auto_copy(). My Dplyr is up-to-date.

![error](https://user-images.githubusercontent.com/34285813/195873732-891c81ea-43a3-45e5-9a46-44cc8e9f319c.jpeg)

**Comment by dbdimitrov** [comment]
Hey @AltayYuzeir,

I did also try it with the orthologous resource. Perhaps, the downsampling gets rid of the exception as I was not able to reproduce it.

**Comment by deeenes** [comment]
I think most likely one of the objects to join has unsuitable type or some other weird stuff such as row names. Maybe you could try to convert `ortholog_resource` to `tibble` or `data.frame` (even if it already has that class). If that doesn't help, you should look at the object on the other side.

**Comment by dbdimitrov** [comment]
Hi @AltayYuzeir,

The issue was coming from NAs in the cell labels. For example, running with the "cluster" works. I have added a check in LIANA that will throw an exception when NAs are detected in cell labels.

However, I leave it up to the user (you) to decide how to deal with those in their data.

Daniel

**Comment by AltayYuzeir** [comment]
That did it! Thank you for your efforts! I will keep this issue in mind going forward. I am closing the issue now.
