### ISSUE TITLE
LIANA for bulk RNA seq?

### ISSUE THREAD

**Issue by alhadjil** [saezlab/liana#64]
Hi,

thanks for this nice package, which works smoothly on scRNASeq datasets. Is it possible to use LIANA for two (or more) bulk RNASeq datasets for CCC?

Thanks!

**Comment by dbdimitrov** [comment]
Hi @alhadjil,

Thanks. LIANA does not currently support bulk RNA-seq. 

An easy way to apply it to bulk would be to use the stats from your DE contrasts join them to known LR interactions (coming e.g. from LIANA's databases), and simply calculate a mean between a ligand and receptor.

Daniel
