### ISSUE TITLE
rlang invoke deprecated 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [saezlab/liana#65]
Hi ! 
I got this message. Maybe in the next version update the rlang usage ?
 ```Avis : `invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.```

thanks in advance

R 4.2.1
liana : 0.1.6

**Comment by BenjaminDEMAILLE** [comment]
Thanks. 
What's will happen if rlang delete this function in a next version ?

**Comment by dbdimitrov** [comment]
I would then replace it with something like this:
https://stackoverflow.com/questions/60678764/now-that-invoke-is-soft-deprecated-whats-the-alternative
