### ISSUE TITLE
Integrated Seurat datasets

### ISSUE THREAD

**Issue by AltayYuzeir** [saezlab/liana#69]
Hello. I have a question regarding using LIANA with multiple integrated scRNA datasets, based on this tutorial: https://satijalab.org/seurat/articles/integration_introduction.html. Does the methods implemented in LIANA account for the differences such as sequencing technology or sequencing depth between the different datasets? Upon following the tutorial you get an "integrated" assay, but you need to run LIANA with the default "RNA" assay, as the "integrated" assay contains negative values.

**Comment by dbdimitrov** [comment]
Hi @AltayYuzeir, the integrated assay from Seurat is not typically intended to be used /w LIANA. As you will notice also from the tutorial, they switch back to RNA right after integration.

Instead, you should use it solely to identify common cell clusters across your samples, and then use the log-normalized or SCT-normalized counts.

**Comment by AltayYuzeir** [comment]
I see, thank you.
