### ISSUE TITLE
error importing conda environment

### ISSUE THREAD

**Issue by wfma** [saezlab/liana#7]
Hi again,

When I import your .yaml for my conda environment, I get the following error message: 

```
ResolvePackageNotFound: 
- libgcc-devel_linux-64=9.3.0
- _openmp_mutex=4.5
- gxx_impl_linux-64=9.3.0
- gfortran_impl_linux-64=9.3.0
- binutils_linux-64=2.35
- libgcc-ng=9.3.0
- libgfortran-ng=9.3.0
- gfortran_linux-64=9.3.0
- gxx_linux-64=9.3.0
- libstdcxx-ng=9.3.0
- gcc_impl_linux-64=9.3.0
- libgomp=9.3.0
- libstdcxx-devel_linux-64=9.3.0
- gcc_linux-64=9.3.0

```
From [other posts](https://github.com/datitran/object_detector_app/issues/41) it seems that its because the original .yaml was exported from a different platform. I am tryin to run it on a mac pro on Big Sur. What do you suggest the best next step is?

Thanks a bunch,
Wei

**Comment by dbdimitrov** [comment]
Dear Wei,

Thank you for opening all these issues and for your patience.

I have now removed the linux-specific dependencies, ran checks on a MAC of a colleague of mine, so it should now work appropriately.

I plan to soon re-implement some of the methods completely in R, so these dependency complications should be resolved.

Thanks,
Daniel

**Comment by wfma** [comment]
Hi Daniel, thanks for setting this up so quickly!

I will attempt to do it again now. It would be SUPER helpful if the dependency on NATMI (and other python-based tools) can be optional when loading in the mean time. It would be phenomenal if you reimplement the python ones into R that way I (and others) can build it into our workflow easier.

Ill report back with any issues!

**Comment by wfma** [comment]
Hmm, it looks like libgcc-ng=9.3.0 is not available. 

```
(base) wm5wt@WeisMac ~ % conda env create -f Desktop/liana-master/liana_env.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - libgcc-ng=9.3.0
```

I tried to get libgcc-ng straight from anaconda
```
(base) wm5wt@WeisMac ~ % conda install -c anaconda libgcc-ng=9.3.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - libgcc-ng=9.3.0

Current channels:

  - https://conda.anaconda.org/anaconda/osx-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Looks like this is also a linux package?
Wei

**Comment by dbdimitrov** [comment]
Hi Wei,

Yes, it appears to be the case - I have now properly excluded it from the conda environment.
Also, technically you can omit the python-based methods, but I'm not certain if this leaves you with much options if you exclude 2 out of the 6 methods.

As you note, I do plan to re-implement NATMI specifically, while Squidpy I will keep due to it's more complex algorithm and very efficient implementation.

Thanks again,
Daniel

**Comment by wfma** [comment]
Awesome! You da best. Ill try it again now and report back if I have an issues. BTW if you need a tester for future implementations let me know! :)
