### ISSUE TITLE
Ordering interactions on liana_dotplot

### ISSUE THREAD

**Issue by clb94** [saezlab/liana#72]
Hi there,

Thanks so much for your work on the liana package, it has been a great help to me. I have a question about the liana_dotplot function which I hope will be quick and easy to answer!

Having worked through the tutorial you kindly provided (https://saezlab.github.io/liana/articles/liana_tutorial.html#citation), I prepared a dotplot from my own scRNAseq data using the liana_dotplot function. I did this after filtering the liana_aggregate output for ligand complexes of interest - I just wanted to compare these interactions with each other.

On the tutorial page, it states: _"By_ default, liana_aggregate would order LIANA’s output according to rank_aggregate in ascending order."_ I am assuming here that rank_aggregate is the same as aggregate_rank, which I also note you suggest as a proxy for p-value.

However, on my dotplot I have noticed that the interaction with the lowest aggregate_rank, which I understand should be interpreted as that with the lowest and most significant p-value, is appearing below other interactions with a higher aggregate_rank. I do think however that those shown are the top 25 most significant interactions, as specified, just not listed in order on the figure.

Please could someone confirm what the default ordering system is for the Y-axis of interactions on the liana_dotplot? I also don't think it is the natmi specificity score as the interaction in question also has the highest specificity. Alternatively, if someone could let me know how to reorder these top interactions in ascending aggregate_rank I would really appreciate it!

Thanks a lot,
Christina

**Comment by enblacar** [comment]
Hi @dbdimitrov,

I can confirm that it is due to the fact that ggplot2 sets the levels of the factors automatically. Once you set them manually to follow the unique values of the interacting pair after subsetting by `top_interactions`, the resulting plot follows the order of the input matrix.

I will also update `SCpubr` accordingly. Very nice point the one brought up in this issue!

Best,
Enrique

**Comment by dbdimitrov** [comment]
Hi @clb94,

I have now updated liana, and interactions will be ordered as in the dataframe that is passed to liana's dotplot.

Best,
Daniel
