### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by haripazhayath** [saezlab/liana#73]
Hi There,

I am facing an issue with installation of the package

remotes::install_github('saezlab/liana')
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

Could you please help

**Comment by dbdimitrov** [comment]
Hi @haripazhayath,

I wasn't able to reproduce your error.

Could you give this line a try:
`remotes::install_github("saezlab/liana", ref="0.1.7")`

**Comment by haripazhayath** [comment]
That still gives the same error

**Comment by haripazhayath** [comment]
I have installed R packages using conda and then git cloned the repository installed this package

Thanks
