### ISSUE TITLE
failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by HuatingYuan** [saezlab/liana#74]
This is what I got when installing

online
remotes::install_github("saezlab/liana")
Error: Failed to install 'unknown package' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed

local
install_local(path="C:/Users/lenovo/Downloads/temp/liana-master.zip")
Error: Failed to install 'liana-master.zip' from local:
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by deeenes** [comment]
From the docs of another software, but valid for this situation: https://pypath.omnipathdb.org/notebooks/manual.html#TLS-(SSL,-HTTPS)-errors
