### ISSUE TITLE
Error when installing on windiws

### ISSUE THREAD

**Issue by pxd98** [saezlab/liana#77]
Hello,
I want to install liana on win11 but got error. My env is R4.1.2. Have you encountered this error?
```
* checking for file 'C:\Users\Users\AppData\Local\Temp\RtmpUHbPIs\remotes4c4871b734b3\saezlab-liana-683ba35/DESCRIPTION' ... OK
* preparing 'liana':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'liana_0.1.9.tar.gz'
* installing *source* package 'liana' ...
** using staged installation
Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'liana'
* removing 'D:/R-4.1.2/library/liana'
```
It seems to be run on linux but my computer is windows.

I also tried to install a older versoin with    remotes::install_github('saezlab/liana',ref="0.1.7")  , but got another error:
```
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'liana' in library.dynam(lib, package, package.lib):
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'D:/R-4.1.2/library/liana'
```
My computer is x86_64.

Thanks.

**Comment by dbdimitrov** [comment]
Hi,

A github issue related to the first one:
https://stackoverflow.com/questions/62393693/warning-in-systemsh-configure-win-sh-not-found

Another related to the second one:
https://github.com/mne-tools/mne-r/issues/5

Let me know if this helps, with the windows issue, perhaps I could add a note as other might also encounter it :)

Daniel

**Comment by pxd98** [comment]
> Hi,
> 
> A github issue related to the first one: https://stackoverflow.com/questions/62393693/warning-in-systemsh-configure-win-sh-not-found
> 
> Another related to the second one: [mne-tools/mne-r#5](https://github.com/mne-tools/mne-r/issues/5)
> 
> Let me know if this helps, with the windows issue, perhaps I could add a note as other might also encounter it :)
> 
> Daniel

Thank you for your answer, it works successfully. 
I'm so sorry that I forgot to reply you because I use another computer to solve that.

Best regards.
