### ISSUE TITLE
A liana consensus resource for commercial using

### ISSUE THREAD

**Issue by menglinzheng0504** [saezlab/liana#79]
Hello!

thank you for the development of Liana package. Is there a parameter of LIANA to generate the consensus only including commercial-use databases? Thanks.

Best,

**Comment by dbdimitrov** [comment]
Hi @menglinzheng0504,

From the figure that you shared, I believe Cellinker is the only potentially problematic resource in LIANA's consensus resource. 

Perhaps, using the `OmnipathR::curated_ligand_receptor_interactions` function to only include the comercial-use databases is the easiest and safest way to get a resource, similar to the consensus resource in LIANA.

Hope this helps.

Daniel

@deeenes any input on this would be appreciated :)

**Comment by dbdimitrov** [comment]
@menglinzheng0504 

Would you mind sharing your commecrial-use figure that you sent to me via email here?
Could help @deeenes with potentially providing better advice in your case and others :)

**Comment by menglinzheng0504** [comment]
Hi @dbdimitrov 

Thank you for your reply. Here is the summary of the resources based on licenses

<img width="434" alt="Screenshot 2023-01-04 103408" src="https://user-images.githubusercontent.com/104495747/210525453-0fba8b7d-950d-4857-9880-221f87f288d6.png">
