### ISSUE TITLE
Liana to compare conditions

### ISSUE THREAD

**Issue by nasjr08** [saezlab/liana#80]
The liana resource is a terrific tool for assessment of cell-cell communication but I was wondering if an implementation of the resource that incorporates multi-condition datasets is available. in other words, If I have a dataset from disease and control where the same celltypes are captured, I would like to compare how cell-cell communication changes between disease and control. CellChat is an example of one of the resources that has introduced this functionality recently. 

Is this something that is available anywhere or this something that is in the works? Further, if I was to split my seuratobj by the conditions and perform the analysis separately, can I deduce changes in L-R communication or would this methodology be invalid? Note that this is something that is performed in the CellChat Resource as shown [here](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/Comparison_analysis_of_multiple_datasets.html) 

Any advice would be much appreciated!

Thank you,
Naseer

**Comment by dbdimitrov** [comment]
Hey Naseer,

Thanks for using LIANA. Indeed, I have implemented a solution for multi-condition (context) data sets in which we use a factorization approach (Tensor-cell2cell) to find hidden CCC patterns.


https://saezlab.github.io/liana/articles/liana_cc2tensor.html

We are also working on providing a protocols manuscript with more in-depth explanations. Will share it here once public.

**Comment by nasjr08** [comment]
Thank you! I'll check it out and have a go!
