### ISSUE TITLE
Unable to choose multiple resources and call_cellchat not working

### ISSUE THREAD

**Issue by shikhanayar** [saezlab/liana#87]
Hello, 

Thank you so much for LIANA! Such a great way to test robustness of findings across different methods and underlying resource utility. I am facing 2 errors, which I was hoping you could help me debug (for context, I am running LIANA on a Seurat rds object).

**Issue 1: selecting multiple resources crashes the run**

- the code I'm using is as follows:
`liana_wrap(sobj,
                        method = c('cellphonedb'),
                        resource = c('CellPhoneDB', 'CellChatDB'),
                        expr_prop=0.1)`
and the error message I receive is as follows:
**Error in if (resource != "custom" & length(setdiff(resource, c(show_resources(),  : 
  the condition has length > 1**

- when I run only one resource (either CellPhoneDB or CellChatDB) I don't face any issues. I also tried defining resources[ as your code shows here](https://github.com/saezlab/ligrec_decouple/blob/main/analysis/comparison/comp_brca_prep.R) and it shows me the same error message as above.

**Issue 2: call_cellchat function fails, even with just using one resource**

- the code I'm using is as follows: 
`liana_wrap(sobj,
                        method = c('call_cellchat'),
                        resource = c('CellChatDB'),
                        expr_prop=0.1)`
and the error message I receive is as follows:
**Error: Can't transform a data frame with duplicate names.**

- my interpretation is that this is occurring at the mutate stage using group labels in the intermediate meta file created, but would appreciate your help on fixing this error

Please let me know if I can provide any other useful items to help with the debugging and thank you in advance!

**Comment by dbdimitrov** [comment]
Hi @shikhanayar,

I couldn't reproduce the first issue, it works with the test data on my machine, and I get a list of results for c('CellPhoneDB', 'CellChatDB') as expected.

```
liana_path <- system.file(package = "liana")
seurat_object <-
    readRDS(file.path(liana_path , "testdata", "input", "testdata.rds"))

liana_res <- liana_wrap(seurat_object, method = c('cellphonedb'), resource = c('CellPhoneDB', 'CellChatDB'), expr_prop=0.1)
```

In the updated version of liana (`0.1.11`), I fixed this issue. 

Hope this helps!

Daniel

**Comment by shikhanayar** [comment]
Thanks Daniel! I'll make sure I have the most updated version of LIANA installed and try to rerun (I'm assuming you meant that you fixed the second issue I mentioned -- using `call_cellchat `as the sole method?).
