### ISSUE TITLE
Multiple seurat objects

### ISSUE THREAD

**Issue by paulyashna** [saezlab/liana#9]
Hi, I would like to input count matrices from multiple Seurat objects. I suppose that is not possible at the moment with Liana. I can beforehand merge the Seurat objects and then input them as a single Seurat object, so should I be merging only the raw counts or the normalized counts assay from Seurat. It will be helpful if you could comment if Liana is using raw counts or the normalized/scaled counts matrice from Seurat.

Thanks for your help.

**Comment by dbdimitrov** [comment]
Hi,

You are correct, currently it's not possible, so you would need to merge them into a single Seurat object.
Each method obtains the log-normalized counts from the 'data' slot of Seurat.

I hope this helps.
Regards,
Daniel

**Comment by paulyashna** [comment]
Thanks for the quick reply. This is helpful.
