### ISSUE TITLE
Default dataset for resources is null

### ISSUE THREAD

**Issue by PoGibas** [saezlab/liana#90]
Default dataset stored in `omni_resources.RDS` seems to be empty while all other resources are data.frames with expected connections. 

```
omni_resources <- readRDS(system.file(package = 'liana', "omni_resources.rds"))
lapply(omni_resources, is.null)
```

Is it a mistake or is such behavior expected and there is a reason for such empty dataset?

**Comment by dbdimitrov** [comment]
Hi @PoGibas,

It's intentional, back when liana was mainly calling external tool this was a way to get the Default resource for each.
