### ISSUE TITLE
chord_freq won't display all labels

### ISSUE THREAD

**Issue by EJCresswell** [saezlab/liana#93]
Hi there,

I've been using chord_freq to generate a pretty frequency chord diagram. I am having issues with this though, as my longer labels extend out of the plot area and I can't seem to get them to display fully. They are also not straight. Is there a way to fix this? I have attached an image.

Thank you

![image](https://user-images.githubusercontent.com/97951071/218460320-6c03f2ae-e314-4d69-a154-f91b3c2f01fd.png)

**Comment by dbdimitrov** [comment]
Hi @EJCresswell,

This is likely something to do with the way that the circlize package works here. I would suggest perhaps trying to export the plot as a larger pdf, so that the labels fit.
