### ISSUE TITLE
Error with liana_wrap()

### ISSUE THREAD

**Issue by ChristinaDing101** [saezlab/liana#94]
Hi,
I encounter a problem when i am trying to run liana_wrap(). 
The Rstudio says as below:
Running LIANA with `Myeloid_Subtype` as labels!
`Idents` were converted to factor
Error in h(simpleError(msg, call)) : 
  在为'rowMeans'函数选择方法时评估'x'参数出了错: size factors should be positive 
此外: Warning message:
In exec(output, ...) :
  10882 genes and/or 0 cells were removed as they had no counts!

However, it is strange that when i manually aggregate some macrophage subsets into one macrophage subset, the problem seems to be gone. I wonder if it happens because some of my macrophage subset only has one to two cells?

**Comment by dbdimitrov** [comment]
Hi @ChristinaDing101,

I believe the small clusters should be filtered out automatically - I.e  anything with less than 10 cells.

Likely there is another issue - e.g. you have negative counts of something similar.

**Comment by dbdimitrov** [comment]
Multiple resolutions to this error message are described here:
https://github.com/saezlab/liana/issues/18

Let me know if any help, alternatively I could try to debug with a small subset of your data.

**Comment by ChristinaDing101** [comment]
Hi @dbdimitrov ,
Thank you for your in time response. With your suggestion, I check my data, and it seems like that my data needs to be normalized first, otherwise it contains negative counts.
Thanks.
