### ISSUE TITLE
Help with experimental design for comparison

### ISSUE THREAD

**Issue by GuiSeSanz** [saezlab/liana#97]
Thanks a lot for this really useful tool! As we are using it, for some simple analysis, when facing a more complex design some questions arose.

We are working with some oncological samples and we have 3 different controls (healthy) and 4 patient data. Each sample is classified into 13 different cellt ypes.
The data from the patient are composed of cancer cells and non-cancerous cells.

We are interested in studying the different interactions: 
1. among the cancerous cells 
2.  the cancerous cells and non-cancerous ones

Our main objective is to identify specific interactions in the patients.
We were thinking about using the interactions from the controls as a comparison baseline in order to remove the basal interactions from the cells.

We are following the tutorial on Tensor-cell2cell Decomposition, and we have questions about the _samplekey_  _conditionkey_ and _groupby_ parameters.

We thought that the _samplekey_ should be the sample identifier (patientID and controlID), the _conditionkey_ should be the combination of the cell type with the category of the cell (cancerous, non-cancerous and healthy) and the _groupby_ keep it as cell type.

This model will yield predictions between healthy cells and cancerous/non-cancerous cells? Those interactions are not really possible, so we filter them?
Is this experimental design correct?

**Comment by dbdimitrov** [comment]
Hi @GuiSeSanz,

How you assign the sample key sounds correct. Indeed, this should ultimately represent different samples. Also, indeed groupby (idents_col in R) should be the cell types.

The condition key should be metadata associated with the samples alone - e.g. cancerous or healthy.

The way that Tensor decomposition works is that it's hypothesis- and design-free. So, ultimately conditions are just there for visualization purposes, while the factorization will return factors which potentially separate the conditions, if the condition label is the a driver of change.  When working with Tensor, it's also assumed that most cell types are should be shared between the samples.
