### ISSUE TITLE
Inherit levels of idents

### ISSUE THREAD

**Issue by fbnrst** [saezlab/liana#99]
This is more a nice-to-have feature request, but I came across this now a couple of times. For me, it would be nice, if `liana_wrap` would inherit the levels of the cluster identities, because this would ensure consistent order of clusters in plotting. Using the tutorial example:

```R
library(liana)
library(Seurat)
liana_path <- system.file(package = "liana")
testdata <-
  readRDS(file.path(liana_path , "testdata", "input", "testdata.rds"))

liana_test <- liana_wrap(testdata, method=c("sca"), )
```

Here, the clusters in the `testdata` Seurat object are a factor:

```R
> levels(Idents(testdata))
'B''CD8 T''NK'
```

and it would be nice if those levels would be inherited to `source` and `target` in `liana_test`, I think. Currently, `liana_test` does not return factors for those:

```R
> levels(liana_test$source)
NULL
```

Of course, one can just convert the source and target columns to factors manually as a workaround.

**Comment by dbdimitrov** [comment]
Hi @fbnrst,

Great point! I'll make sure to keep the levels in next update.

Daniel

**Comment by dbdimitrov** [comment]
LIANA now properly inherits these :)
